### ISSUE TITLE
Advanced documentation

### ISSUE THREAD

**Issue by badlydrawnrob** [badlydrawnrob/anki-child-theme#1]
> Simplify! Build for your future stupid self.

- [ ] [Beginner and Advanced](https://github.com/badlydrawnrob/anki/issues/54) documentation
- [ ] [Building custom themes](https://github.com/badlydrawnrob/anki/issues/73)
- [ ] [Save the Pandoc docs for the professionals](https://github.com/badlydrawnrob/anki/issues/69)
- [ ] [Potentially add more colours](https://github.com/badlydrawnrob/anki/issues/52)
- [ ] [Explore font stacks](https://github.com/badlydrawnrob/anki/issues/12)
